Extend `chunk` to take `size` as an argument
JuliaML/MLUtils.jl pull request #112
Opened 2022-07-06 13:02 UTC by theabhirath

Should close #109. I would've left this to the author of that issue but I need this for some of the Metalhead.jl work on Res2Net.

---
This PR extends `chunk` to expect an optional kwarg `size`, which should return chunks of size `size`. I've rewritten the way `chunk(x, n)` works since that seemed a natural extension and tests pass, but I'm not an expert at the `rrule` stuff so if there's something wrong feedback would be appreciated 😅

2022-07-06 21:52 UTC, gruberchr requested changes
Adding method `chunk(x; size)` looks good to me. A test for the new method is still missing. Or is it sufficient to test it implicitly via method `chunk(x, n)`?
Additionally I added some comments suggesting to use function `cld()` for simplification.
I'm not familiar with writing `rrule`s as well, therefore I'm not able to check that.

2022-07-06 21:52 UTC, gruberchr commented on src/utils.jl
> +chunk(x::AbstractArray, n::Int; dims::Int=ndims(x)) = chunk(x; size = ceil(Int, size(x, dims) / n), dims)
`ceil(Int, size(x, dims) / n)` could be replaced by `cld(size(x, dims), n)`.

2022-07-06 21:52 UTC, gruberchr commented on test/utils.jl
> +    idxs = MLUtils._partition_idxs(x, ceil(Int, size(x, dims) / n), dims)
`ceil(Int, size(x, dims) / n)` could be replaced by `cld(size(x, dims), n)`.

2022-07-07 03:51 UTC, theabhirath commented
Thanks for the comments! I've changed the code to use `cld`, and I've also added some tests with `chunk` taking in `size`

2022-07-07 03:51 UTC, theabhirath commented on src/utils.jl
> +chunk(x, n::Int) = chunk(x; size = ceil(Int, length(x) / n))
Thanks for this!

2022-07-07 06:40 UTC, gruberchr commented
:+1:

2022-07-08 23:26 UTC, darsnack approved these changes

2022-07-10 17:24 UTC, theabhirath commented
Bump?

2022-07-10 18:56 UTC, merged